### PR TITLE
fix(utils): remove warning for missing kerberos module

### PR DESCRIPTION
**Pull request by kvwalker**
Fixes [NODE-1626](https://jira.mongodb.org/browse/NODE-1626)

### CODE REVIEW

**Comment by daprahamian** [comment]
Doesn't this leave us back in the situation where a kerberos require error can be swallowed and confuse people?

**Comment by kvwalker** [comment]
@daprahamian, I thought there was a reason this was added in the first place...do you remember what the ticket was for that problem? In this case, it seems preferable to keep the warning the way it currently is.

**Comment by daprahamian** [comment]
@kvwalker I'm not sure. The [commit](https://github.com/mongodb-js/mongodb-core/commit/b553ee17e7377b4943af29ce0847598a246ed6f2#diff-50e3aa130a4f97a42ee2cf111c7b1d9d) is not really helpful. But I think a better approach might be to store the Error, and then if anyone tries to auth with Kerberos throw the error?

**Comment by mbroadst** [comment]
@daprahamian I think what we should do here is ignore any error related to the requiring of the module, and rethrow other errors. Users should not have to pay the price here for what we are already calling an optional requirement. The problem with the code as its written is that it will _also_ swallow any errors caused during the import (this bit me yesterday, a syntax error resulted in a message that kerberos was missing). Are there other classes or error you are concerned about being confusing?

**Comment by kvwalker** [comment]
@daprahamian, we should be able to check if `error.code === 'MODULE_NOT_FOUND'`, according to https://nodejs.org/api/modules.html#modules_file_modules.

**Comment by daprahamian** [comment]
Okay, then lets do that and test it.

**Comment by kvwalker** [comment]
Closing this for Matt's refactor.

**Pull request closed without merging**
