### PR TITLE
fix(cursor): do not truncate an existing Long

### PR DESCRIPTION
**Pull request by jasontho-ms**
This is a fix for issue #440

### CODE REVIEW

**Comment by daprahamian** [comment]
@jasontho-ms are you sure this is necessary? I just ran the following in the terminal and it seems okay.

```js
const bson = require('bson');
const assert = require('assert');

assert.ok(bson.Long.fromNumber(bson.Long.MAX_VALUE).equals(bson.Long.MAX_VALUE))
```

**Comment by jasontho-ms** [comment]
MAX_VALUE has no low bits so it works, but try it with one less than MAX_VALUE so it has low bits:

> bson.Long.MAX_VALUE.toString()
'9223372036854775807'
> const foo = bson.Long.fromString('9223372036854775806')
> foo
Long { _bsontype: 'Long', low_: -2, high_: 2147483647 }
> assert.ok(bson.Long.fromNumber(foo).equals(foo))
AssertionError [ERR_ASSERTION]: false == true
>

**Comment by daprahamian** [comment]
@jasontho-ms Ah, good point.

**Comment by jasontho-ms** [comment]
Internet points don’t matter 😊 I’d appreciate it if you port it over. Thanks for taking a look!

**Comment by daprahamian** [comment]
Merged. Thank you for the contribution @jasontho-ms!

**Pull request merged**
