### PR TITLE
fix(uri_parser): uri-encoded auth handling

### PR DESCRIPTION
**Pull request by tprobinson**
Change options and auth handling to leverage parsed URI object

When using a `mongodb+srv://` record and a password containing certain special characters, the URI would be perceived as malformed, even if the password was URI-encoded. This PR fixes the password handling to be more in line with non-SRV parsing.

### CODE REVIEW

**Comment by mbroadst** [comment]
Hey @tprobinson, thanks for the PR! Any chance you could provide some tests exemplifying the issues you faced that brought you to this solution?

**Comment by tprobinson** [comment]
I've added some tests to both the `mongodb://` and `mongodb+srv://` parsers, they fail on the commit prior to my fix. If there's anything else I can do, please let me know!

**Comment by mbroadst** [comment]
@tprobinson thanks! Those spec tests are actually copied in from our specifications repo for all drivers. I'll see what I can do about getting those pushed up there.

**Comment by mbroadst** [comment]
@tprobinson hey! I've got PRs up to get the tests added to our specs repo, sorry to do this but can you actually _remove_ them from this PR and we'll merge? 😈

**Comment by tprobinson** [comment]
@mbroadst Done!

**Comment by mbroadst** [comment]
@tprobinson cheers! Release going out by end of day, thanks for the contribution!

**Comment by tprobinson** [comment]
Thanks for the speedy review and merge!
-------- Original Message --------

**Pull request merged**
